# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
