# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181111_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
