# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181115_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='fooditem',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='fooditem',
            new_name='food',
        ),
    ]
