# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181127_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodinfo', to='api.Food'),
        ),
    ]
