# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181129_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
